[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
ignore_missing_imports = False
install_types = True

[mypy-observability.*]
ignore_missing_imports = True
follow_imports = silent

[mypy-auth.*]
ignore_missing_imports = True
follow_imports = silent

[mypy-routes.*]
ignore_missing_imports = True
follow_imports = silent
